version: '2'
services:
  ecomshop-app:
    image: ecomshop
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://ecomshop-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=EcomShop
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://ecomshop-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://ecomshop-elasticsearch:9200
    ports:
      - 8080:8080
  ecomshop-mongodb:
    extends:
      file: mongodb.yml
      service: ecomshop-mongodb
  ecomshop-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: ecomshop-elasticsearch
