version: '2'
services:
  ecomshop-mongodb:
    image: mongo:4.0.16
    ports:
      - '27017:27017'
    command: mongos --configdb ecomshop-mongodb-config
  ecomshop-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  ecomshop-mongodb-config:
    image: mongo:4.0.16
    container_name: ecomshop-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
